// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrhnunucluajfoewdxpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yaG51bnVjbHVhamZvZXdkeHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTY4MjIsImV4cCI6MjA1OTU5MjgyMn0.CzirojJ1skGSY3lATRgYy8P9oZFEK3QJAltIBfJzgPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);